### PR TITLE
Add the Developer Guide in README

### PR DESCRIPTION
**Pull request by Harshil-Jani**
The PR is intended to bring out the developer guide into the README of the project.

### CODE REVIEW

**Comment by amadio** [comment]
Hi @Harshil-Jani, thank you for the pull request! I did get a request to document the whole procedure to build/run g4run to generate a report, so your contribution comes quite handy. However, there are some things that need to be changed. What I'd like to document is how to run the CI version of the report using the script `ci/jenkins.sh`, and that takes care of building Geant4 for you, so you really should only need the dependencies of Geant4 installed. Also, the g4web report hard-codes pythia for now, and won't work when you do not have Pythia available. We need to fix that or mention in the documentation that the HTML report needs Pythia to be enabled. I think that the scripts that generate the data needed by the report will work with runs other than Pythia, but I have not had the time to test everything yet.

**Comment by Harshil-Jani** [comment]
Thankyou for the feedback @amadio ! I think I can test this in upcoming week and confirm how it works now. And I will change/add the descriptive for running the Jenkins script considering the dependencies of Geant4.

**Comment by amadio** [comment]
Just to get you started, you need a `git/geant4.git` with a bare clone of Geant4 within `g4run`'s repository, then you can call `env GIT_PREVIOUS_COMMIT=version1 GIT_COMMIT=version2 ci/jenkins.sh` to run the build, where `version1` and `version2` are two git tags from the Geant4 git repository. I believe that I also assume CVMFS to be available in the Jenkins script, so you may have to install that so that it uses data files from `/cvmfs` instead of having to install it every time.

**Comment by Harshil-Jani** [comment]
@amadio Please have a look at the document and let me know if it looks good ! Thankyou.

**Comment by amadio** [comment]
Thanks for the contribution, @Harshil-Jani! Sorry for the delay, things are quite busy here these days, as I'm transitioning to the IT department next year.

**Comment by Harshil-Jani** [comment]
Thankyou @amadio for merging the Pull.
>  I'm transitioning to the IT department next year.

Glad to hear that. BTW currently are you in Experimental Physics Department ?

**Comment by amadio** [comment]
Yes, in EP now, and moving to IT.

**Pull request merged**
